default_platform(:android)

platform :android do
  github_url = "git@github.com"
  import_from_git(url: "#{github_url}:Taki-Kun/fastlane-common.git", branch: "master", path: "fastlane/Fastfile")
  import_from_git(url: "#{github_url}:Taki-Kun/fastlane-ios.git", branch: "master", path: "fastlane/Fastfile")
end
